name: Test with markdownlint-cli2

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v10
        with:
          globs: '**/*.md'
